version: '3.9'
services:

  server:
    container_name: server
    build: server/ 
    ports:
      - 8081:8081
    restart: on-failure
    volumes:
      - server:/usr/src/app
    environment:
            - PORT=8081
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_USERNAME=root
            - DB_PASSWORD=birmingham
            - DB_DATABASE=currencyconverter
            - JWT_SECRET='{dZqC_/KBzNSuPT~@!Gr5NHG^j]Jz"VQf(6>Q,\dp?_z9eC(C$-bJCEwRM}pC=2!'

volumes:
  server: